source 'https://rubygems.org'


gem 'rails', '4.2.6'

gem 'rails-api'

gem 'pg'

gem 'devise', '~> 3.5', '>= 3.5.6'

gem 'reform', '~> 2.1'

# gem 'active_model_serializers', '~> 0.10.0.rc4'
gem 'active_model_serializers', '~> 0.9.4'

gem 'rack-cors', '~> 0.4.0'


group :development do
  gem 'annotate', '~> 2.7'
  gem 'spring'
  gem 'thin'
  gem 'rspec-rails', '~> 3.4', '>= 3.4.2'
  gem 'factory_girl_rails', '~> 4.6'
  gem 'faker', '~> 1.6', '>= 1.6.3'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
